# Generated by Django 3.2 on 2021-05-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('major', models.CharField(max_length=100)),
                ('bd', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='writer',
            new_name='nickname',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='blog',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
