# Generated by Django 3.2 on 2021-05-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_team_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='place',
            new_name='residence',
        ),
    ]
