# Generated by Django 3.2 on 2021-05-13 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_place_team_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='MBTI',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
