# Generated by Django 3.2 on 2021-05-13 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_team_mbti'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='INTRO',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
