# Generated by Django 3.2.2 on 2021-05-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albamon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=200)),
                ('requirement', models.CharField(max_length=500)),
                ('wage', models.IntegerField()),
                ('job', models.TextField()),
                ('number', models.IntegerField()),
            ],
        ),
    ]
